SaleManagement/Models/BranchDTO.cs
using System.ComponentModel.DataAnnotations;

namespace SaleManagement.Models
{
    public class BranchDTO
    {
        public string BranchId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
    }
}

SaleManagement/Models/ErrorViewModel.cs
namespace SaleManagement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SaleManagement/Models/RequestDTO.cs
using SaleManagement.Utility;
using static SaleManagement.Utility.SD;

namespace SaleManagement.Models
{
    public class RequestDTO
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
    }
}

SaleManagement/Models/ResponseDTO.cs
namespace SaleManagement.Models
{
    public class ResponseDTO
    {
		public object? Result { get; set; }
		public bool IsSuccess { get; set; } = true;
		public string Message { get; set; } = "";
	}
}

SaleManagement/Controllers/BranchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SaleManagement.Models;
using SaleManagement.Service.IService;
using SaleManagement.Utility;

namespace SaleManagement.Controllers
{
    public class BranchController : Controller
    {
        private readonly IBranchService _branchService;
        public BranchController(IBranchService branchService)
        {
            _branchService = branchService;
        }
        public async Task<IActionResult> BranchIndex()
        {
            List<BranchDTO> list = new();

            ResponseDTO? response = await _branchService.GetAllBranchAsync();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<BranchDTO>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }

            return View(list);
        }

        public async Task<IActionResult> BranchCreate()
        {
            var selectLists = new List<SelectListItem>()
           {
               new SelectListItem {Text = SD.ActiveState,Value=SD.ActiveState },
               new SelectListItem {Text = SD.DeActiveState, Value=SD.DeActiveState },
           };
            ViewBag.State = selectLists;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BranchCreate(BranchDTO product)
        {

            if (ModelState.IsValid)
            {
                ResponseDTO? response = await _branchService.AddNewBranch(product);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Product created successfully";
                    return RedirectToAction(nameof(BranchIndex));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
                var selectLists = new List<SelectListItem>()
           {
               new SelectListItem {Text = SD.ActiveState,Value=SD.ActiveState },
               new SelectListItem {Text = SD.DeActiveState, Value=SD.DeActiveState },
           };
                ViewBag.State = selectLists;
            }
            return View(product);
        }
        public async Task<IActionResult> DeleteBranch(string branchId)
        {
            ResponseDTO? response = await _branchService.GetBranchById(branchId);

            if (response != null && response.IsSuccess)
            {
                BranchDTO? model = JsonConvert.DeserializeObject<BranchDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteBranch(BranchDTO branch)
        {
            ResponseDTO? response = await _branchService.DeleteBranch(branch.BranchId);
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Product deleted successfully";
                return RedirectToAction(nameof(BranchIndex));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(branch);
        }
		public async Task<IActionResult> BranchEdit(string branchId)
		{
			ResponseDTO? response = await _branchService.GetBranchById(branchId);
            var selectLists = new List<SelectListItem>()
           {
               new SelectListItem {Text = SD.ActiveState,Value=SD.ActiveState },
               new SelectListItem {Text = SD.DeActiveState, Value=SD.DeActiveState },
           };
            ViewBag.State = selectLists;
            if (response != null && response.IsSuccess)
			{
				BranchDTO? model = JsonConvert.DeserializeObject<BranchDTO>(Convert.ToString(response.Result));
				return View(model);
			}
			else
			{
				TempData["error"] = response?.Message;
			}
            
            return NotFound();
		}
		[HttpPost]
		public async Task<IActionResult> BranchEdit(BranchDTO branch)
		{
			ResponseDTO? response = await _branchService.UpdateBranch(branch);
			if (response != null && response.IsSuccess)
			{
				TempData["success"] = "Product updated successfully";
				return RedirectToAction(nameof(BranchIndex));
			}
			else
			{
				TempData["error"] = response?.Message;
			}
            var selectLists = new List<SelectListItem>()
           {
               new SelectListItem {Text = SD.ActiveState,Value=SD.ActiveState },
               new SelectListItem {Text = SD.DeActiveState, Value=SD.DeActiveState },
           };
            ViewBag.State = selectLists;
            return View(branch);
		}
	}
}

SaleManagement/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SaleManagement.Models;
using System.Diagnostics;

namespace SaleManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SaleManagement/Views/Branch/BranchCreate.cshtml
@model BranchDTO

<form asp-action="BranchCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Create Branch</h1>
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Ma chi nhanh</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="BranchId" class="form-control" />
                <span asp-validation-for="BranchId" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Ten chi nhanh</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Dia chi</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Thanh Pho</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Zipcode</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">State</label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="State" class="form-select" asp-items="@ViewBag.State">
                    <option disabled selected>--Select State--</option>
                </select>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="BranchIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}   

SaleManagement/Views/Branch/BranchEdit.cshtml
@model BranchDTO

<form asp-action="BranchEdit" enctype="multipart/form-data">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Edit Product</h1>
        <input hidden asp-for="BranchId" />
        <hr />
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Ten chi nhanh</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Dia chi</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Thanh pho</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input asp-for="City" class="form-control" /> 
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Trang thai</label>
                    </div>
                    <div class="col-10 pb-3">
                        <select asp-for="State" class="form-select" asp-items="@ViewBag.State">
                            <option disabled selected>--Select State--</option>
                        </select>
                    </div>
                    <div class="col-2">
                        <label class="control-label pt-2" style="font-size:20px;">Zipcode</label>
                    </div>
                    <div class="col-10 pb-3">
                        <input asp-for="ZipCode" class="form-control" />
                        <span asp-validation-for="ZipCode" class="text-danger"></span>
                    </div>
                    <div class="col-5 offset-2">
                        <a asp-action="BranchIndex" class="btn-primary btn form-control ">Back to List</a>
                    </div>
                    <div class="col-5">
                        <input type="submit" value="Update" class="btn btn-success form-control" />
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SaleManagement/Views/Branch/BranchIndex.cshtml
@model IEnumerable<BranchDTO>

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-secondary bg-gradient ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white">Branches List</h1>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-action="BranchCreate" class="btn btn-outline-primary"><i class="bi bi-plus-square"></i> Create New Branch</a>
			</div>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>
						Ma Chi Nhanh
					</th>
					<th>
						Ten Chi Nhanh
					</th>
					<th>
						Dia chi
					</th>
					<th>
						Trang thai
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@item.BranchId
						</td>
						<td>
							@item.Name
						</td>
						<td>
							@item.Address
						</td>
						<td>
							@item.State
						</td>
					<td>
							<a class="btn btn-success" asp-action="BranchEdit" asp-route-branchId="@item.BranchId">
								<i class="bi bi-pencil-square"></i>
							</a>
							<a class="btn btn-danger" asp-action="DeleteBranch" asp-route-branchId="@item.BranchId">
								<i class="bi bi-trash"></i>
							</a>
						</td>
					</tr>
				}
			</tbody>
		</table>

	</div>

</div>
@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

SaleManagement/Views/Branch/DeleteBranch.cshtml
@model BranchDTO

<form asp-action="DeleteBranch">
    <br />
    <div class="container border p-3">
        <h1 class="text-white text-center">Delete Branch</h1>
        <input hidden asp-for="BranchId" />
        <hr />
        <div class="row">
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;"> Ma chi nhanh</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="BranchId" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Ten chi nhanh</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Name" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Dia chi</label>
            </div>
            <div class="col-10 pb-3">
                <textarea asp-for="Address" disabled class="form-control" rows="5"></textarea>
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Thanh pho</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="City" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label class="control-label pt-2" style="font-size:20px;">Zipcode</label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="ZipCode" disabled class="form-control" />
            </div>

            <div class="col-5 offset-2">

                <a asp-action="BranchIndex" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>

        </div>

        <div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SaleManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SaleManagement/Views/Shared/_Layout.cshtml
﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SaleManagement.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SaleManagement.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BirdTrading.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <li class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Branch" asp-action="BranchIndex">
                                Manage Branches
                            </a>
                        </li>
                    </ul>
                </li>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notification" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SaleManagement.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SaleManagement/Views/Shared/_Notification.cshtml
﻿@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">toastr.error('@TempData["error"]')</script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">toastr.success('@TempData["success"]')</script>
}